import { sql } from "drizzle-orm";
import { type AnyPgColumn, timestamp, uuid } from "drizzle-orm/pg-core";

/** Primary key: a random UUID generated by Postgres. */
export const id = () => uuid().primaryKey().defaultRandom();

/** `created_at` and `updated_at` (timestamptz). Drizzle sets `updated_at` on every update. */
export const timestamps = () => ({
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** CHECK expression: the text column holds one of `values` (constants from src/constants). */
export function oneOf(column: AnyPgColumn, values: readonly string[]) {
  return sql`${column} in (${sql.raw(values.map((value) => `'${value}'`).join(", "))})`;
}
